### PR TITLE
Use `os.path.sep` instead of hard code slashpath.

### PR DESCRIPTION
**Pull request by dschaper**
Should temporarily fix the win/lin path problems. Not a permanent fix but gets things running.

### CODE REVIEW

**Comment by dschaper** [comment]
@zhimsel It can't be this easy, can it?

**Comment by XhmikosR** [comment]
This doesn't seem to work, I still get the same error. The issue must be somewhere else.

**Comment by XhmikosR** [comment]
Maybe we should replace backslashes in self.doc_pages here?

https://github.com/pi-hole/mkdocs-redirects-redux/blob/master/mkdocs_redirects/plugin.py#L108

**Comment by dschaper** [comment]
Okay, 2.7 is no more as of Jan 2020 so I'll go ahead and just move to 3.4 as the min and use `pathlib`. And shift things over to `poetry` instead of the makefile for deployment.

**Comment by dschaper** [comment]
> 
> 
> Maybe we should replace backslashes in self.doc_pages here?
> 
> https://github.com/pi-hole/mkdocs-redirects-redux/blob/master/mkdocs_redirects/plugin.py#L108

Did you mean to choose the master branch instead of the fix/ospath branch?

**Comment by XhmikosR** [comment]
I confirmed that on Windows the filepaths do have backslashes

```
>self.doc_pages
WARNING -  TRUE '{'index.md': <mkdocs.structure.files.File object at 0x00000220C2A1B9D0>, 'abbreviations.md': <mkdocs.structure.files.File object at 0x00000220C2A1B550>, 'core\\pihole-command.md': <mkdocs.structure.files.File object at 0x00000220C2A1B910>
....
```

So, if one is using forward slashes like I did in the docs PR, those don't match

>Did you mean to choose the master branch instead of the fix/ospath branch?

Yeah, this patch right now is wrong anyway :P

**Comment by XhmikosR** [comment]
2.7 doesn't work anyway with the other plugins

**Comment by dschaper** [comment]
It was just a shot from the hip. I didn't want to dig in to exploding paths and gluing together with `os.path` joins. Just not pretty that way.

**Comment by XhmikosR** [comment]
I will try the other way around later, i.e. replace backslashes with forward slashes in the redirect string itself. This should work in theory, and we should just document that only forward slashes should be used (not that anyone sane would use backslashes IMO :P)

Not sure which solution sounds better, either way we need to streamline the usage of slashes so that it's no OS dependent.

**Comment by XhmikosR** [comment]
Going to close this since it was fixed upstream sometime ago.

**Comment by dschaper** [comment]
Thank you.

**Comment by dschaper** [comment]
Do we still need the fork then?

**Comment by XhmikosR** [comment]
Hmm, probably not, but I started working on fixing some other stuff which I don't know if they'll be merged.

https://github.com/datarobot/mkdocs-redirects/compare/master...pi-hole:dev

**Comment by dschaper** [comment]
Okay, no need to delete the fork if it's being used. Let me know when it's good to clean it up.

**Pull request closed without merging**
